LOCAL_PATH := device/meizu/mblu2

# Architecture
ifeq ($(MBLU2_32_BUILD),true)
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53
else
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
endif

# Audio
USE_XML_AUDIO_POLICY_CONF := 1

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth
BOARD_HAVE_BLUETOOTH := true

# Board
TARGET_BOOTLOADER_BOARD_NAME := mt6735
TARGET_USES_64_BIT_BINDER := true
TARGET_BOARD_PLATFORM := mt6735
TARGET_NO_BOOTLOADER := true
ifneq ($(MBLU2_32_BUILD),true)
TARGET_IS_64_BIT := true
endif

# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true

# DRM
ifneq ($(MBLU2_32_BUILD),true)
TARGET_ENABLE_MEDIADRM_64 := true
endif

# DT2W
TARGET_TAP_TO_WAKE_NODE := /proc/enable_dt2w

# Dexpreopt
ifeq ($(HOST_OS),linux)
ifneq ($(TARGET_BUILD_VARIANT),eng)
ifeq ($(WITH_DEXPREOPT),)
WITH_DEXPREOPT_BOOT_IMG_AND_SYSTEM_SERVER_ONLY := false
WITH_DEXPREOPT := true
endif
endif
endif

# Display
SF_VSYNC_EVENT_PHASE_OFFSET_NS := -8000000
VSYNC_EVENT_PHASE_OFFSET_NS := -8000000
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_USES_HWC2 := true

# HIDL
DEVICE_MATRIX_FILE := $(LOCAL_PATH)/compatibility_matrix.xml
DEVICE_MANIFEST_FILE := $(LOCAL_PATH)/manifest.xml

# Kernel
ifeq ($(MBLU2_32_BUILD),true)
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2
else
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
endif
ifneq ($(TARGET_BUILD_VARIANT),user)
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
endif

TARGET_KERNEL_SOURCE := kernel/meizu/mblu2
TARGET_KERNEL_CONFIG := mblu2_defconfig
BOARD_MKBOOTIMG_ARGS := \
    --board $(TARGET_BOARD_PLATFORM) \
    --kernel_offset 0x8000 \
    --pagesize 2048

ifeq ($(MBLU2_32_BUILD),true)
BOARD_KERNEL_IMAGE_NAME := zImage-dtb
BOARD_MKBOOTIMG_ARGS += \
    --base 0x40000000 \
    --ramdisk_offset 0x4000000 \
    --second_offset 0xF00000 \
    --tags_offset 0xE000000
else
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
BOARD_MKBOOTIMG_ARGS += \
    --base 0x40078000 \
    --ramdisk_offset 0x3F88000 \
    --second_offset 0xE88000 \
    --tags_offset 0xDF88000
endif

# Partitons
BOARD_USERDATAIMAGE_PARTITION_SIZE := 12072779776
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 50331648
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912
BOARD_CACHEIMAGE_PARTITION_SIZE := 104857600
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 131072

# RIL
ENABLE_VENDOR_RIL_SERVICE := true
SIM_COUNT := 2

# Recovery
TARGET_RECOVERY_FSTAB := vendor/meizu/mblu2/proprietary/etc/fstab.mt6735

# Sepolicy
#BOARD_SEPOLICY_DIRS += device/meizu/mblu2/sepolicy

# Treble
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
PRODUCT_FULL_TREBLE_OVERRIDE := true
TARGET_COPY_OUT_VENDOR := vendor
PRODUCT_SHIPPING_API_LEVEL := 22
BOARD_VNDK_VERSION := current

# Vendor security patch level
VENDOR_SECURITY_PATCH := 2019-10-05

# Wi-Fi
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_STATE_CTRL_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_PARAM := "/dev/wmtWifi"
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_P2P := P2P
BOARD_WLAN_DEVICE := MediaTek
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_STATE_OFF := 0
WIFI_DRIVER_STATE_ON := 1
